spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3306/eshop
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    
server:
  port: 8000
  
  
