spring:
  application:
    name: user-service

  datasource:
    url: ${User.db.rds.url}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${User.db.rds.username}
    password: ${User.db.rds.password}
    
server:
  port: ${User.Service.port}
  
  
