spring:
  application:
    name: eureka-naming-server
    
  datasource:
    url: jdbc:mysql://localhost:3306/eshop
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    
server:
  port: 8761
  
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false