
spring:
  application:
    name: cart-service

  datasource:
    url: jdbc:mysql://localhost:3306/eshop
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    
  jpa:
   hibernate:
    ddl-auto: update
   show-sql: true
   database-platform: org.hibernate.dialect.MySQL5Dialect

server:
  port: 8200
  
eureka:
  client:
    eureka-server-port: 8761